1- Formação Desenvolvedor .NET/3 - Fundamentos do ASP.NET MVC/08 - Desenvolvendo uma aplicação funcional/Aula 02 - Conhecendo o ASP.NET Identity/PrimeiraApp/ViewComponents/SaudacaoAlunoViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using PrimeiraApp.Models;

namespace PrimeiraApp.ViewComponents
{
    public class SaudacaoAlunoViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            // Pegar o aluno lá na base de dados!!!
            // Pegar o dado (nome) do aluno que está logado!
            var aluno = new Aluno() { Nome = "Eduardo" };

            return View(aluno);
        }
    }
}

1- Formação Desenvolvedor .NET/3 - Fundamentos do ASP.NET MVC/08 - Desenvolvendo uma aplicação funcional/Aula 02 - Conhecendo o ASP.NET Identity/PrimeiraApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PrimeiraApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PrimeiraApp.styles.css" asp-append-version="true" />
</head>
<body>
    
    <partial name="_MenuLayout" />

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PrimeiraApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>

            <vc:saudacao-aluno />

            @*@await Component.InvokeAsync("SaudacaoAluno")*@
        </div>
    </footer>    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

1- Formação Desenvolvedor .NET/3 - Fundamentos do ASP.NET MVC/08 - Desenvolvendo uma aplicação funcional/Aula 02 - Conhecendo o ASP.NET Identity/PrimeiraApp/Views/Shared/_MenuLayout.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PrimeiraApp</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>